### ISSUE TITLE
Should add .gitignore file for repos at root directory

### ISSUE THREAD

**Issue by dinhanhx** [miatran1109/AlarmOneClock#18]
[Here](https://github.com/miatran1109/AlarmOneClock/tree/master/app/build/test-results/testReleaseUnitTest/binary) and [here](https://github.com/miatran1109/AlarmOneClock/tree/master/app/build/test-results/testDebugUnitTest/binary) are binary files so you should ignore them
`.gitignore` file
```
*.bin
```
You can make 1 for all .gitignore file for the whole repos.

**Comment by miatran1109** [comment]
Thanks, so that's how it should be.
solve here: 366472643687532ad7dbced032d4a43227b188b7
